# Generated by Django 6.0.5 on 2026-06-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=90)),
                ('prioridade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='baixo', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('probabilidade_perda', models.PositiveIntegerField(default=0)),
                ('valor_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('acao_sugerida', models.CharField(max_length=255)),
                ('risco', models.CharField(default='baixo', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('perdida', 'Perdida')], default='aberta', max_length=20)),
                ('data_reagendamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='empresas.empresa')),
            ],
            options={
                'ordering': ['prioridade', '-valor_potencial'],
                'indexes': [models.Index(fields=['status', 'prioridade'], name='oportunidad_status_603074_idx'), models.Index(fields=['empresa', 'status'], name='oportunidad_empresa_136ac1_idx')],
            },
        ),
    ]
