# Generated by Django 6.0.5 on 2026-06-11 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('MASTER', 'Master'), ('GESTORA_RELACIONAMENTO', 'Gestora de Relacionamento'), ('ANALISTA', 'Analista')], default='ANALISTA', max_length=40)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aleica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
