# Generated by Django 6.0.5 on 2026-06-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_aleica', models.PositiveIntegerField(default=0)),
                ('risco', models.CharField(max_length=20)),
                ('probabilidade_perda', models.PositiveIntegerField(default=0)),
                ('dias_sem_retorno', models.PositiveIntegerField(default=0)),
                ('valor_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo_alerta', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_inteligencia', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
