CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS cliente;
CREATE SCHEMA IF NOT EXISTS contrato;
CREATE SCHEMA IF NOT EXISTS financeiro;
CREATE SCHEMA IF NOT EXISTS documento;
CREATE SCHEMA IF NOT EXISTS relatorio;
CREATE SCHEMA IF NOT EXISTS auditoria;

